### ISSUE TITLE
Remove `step`

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/Windshaft-cartodb#1010]
We were removing `step` from some modules we noticed that some metrics were improving. Let's remove `step` to handle async code in favor of Node.js callback pattern as long as possible.

Let's go module by module with its own PR, for instance:

- [x]  #1011 `lib/cartodb/backends/dataview.js` -> `remove-step-dataviews` @dgaubert
- [x]  #1012 `lib/cartodb/backends/filter-stats.js` -> `remove-step-filter-stats` @oleurud 
- [x]  #1016 `lib/cartodb/backends/template_maps.js` -> `remove-step-template-maps` @dgaubert
- [x]  #1013 `lib/cartodb/backends/user-limits.js` -> `remove-step-user-limits` @oleurud 
- [x]  #1014 `lib/cartodb/models/mapconfig/adapter/mapconfig-overviews-adapter.js` -> `remove-step-mapconfig-overviews-adapter` @oleurud
