### ISSUE TITLE
[node-v6] [mapnik-v3] Node v6 LTS and Mapnik v3.x support 

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/Windshaft-cartodb#612]
Support for Node 0.10.x has ended in October 2016. We need to migrate to the latest Node LTS version (`v6.9.1`)
 
## TODO
 - [x] #611 Upgrade windshaft
 - [x] #610 Upgrade redis-mpool
 - [x] #609 Upgrade cartodb-psql 
 - [x] #608 Upgrade cartodb-redis
 - [x] #607 Upgrade camshaft

**Comment by dgaubert** [comment]
PR: #635 [DO NOT MERGE YET]

**Comment by rafatower** [comment]
Deploy blocked by performance issue: https://github.com/CartoDB/Windshaft-cartodb/issues/648

**Comment by dgaubert** [comment]
Closing 3, 2, 1
