### ISSUE TITLE
Mapnik3-node6 performance issues

### ISSUE THREAD

**Issue by rafatower** [CartoDB/Windshaft-cartodb#648]
### Description of the issue
During the deployment of mapni3+node6 we've noticed some performance issues:
- 95 and 99 percentile times are much worse than expected.
- Map instantiation is slower than in previous version (kind of expected)

Some remarks:
- Memory usage is also bigger but doesn't seem to be an issue
- The 95p and 99p represent the worst cases. We suspect of garbage collection blocking for too long. We monitor the GC cycles forced by us periodically (every 10s?) but not the ones that are triggered automatically by node6.
- Map instantiation implements a full css parser rather than just a regexp.

### Action plan
- [ ] Investigate root cause(s)
- [ ] Change benchmarks to cover these cases
- [ ] Fix it
- [ ] Postmortem
- [ ] Add new metrics if needed
