### ISSUE TITLE
Manage multiple values of buffer-size for different formats

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/Windshaft-cartodb#665]
We're going to need to manage different values of `buffer-size` for different formats so we need to make some changes:

#### Tasks

- [ ] Should be able to receive different configurations for the buffer-size for environment 
        configuration: dictionary with different `buffer-size` per format
- [ ] Create renderer using proper `buffer-size` for the requested format
- [ ] Named maps should have a template for the `buffer-size` property so the user could create multiple instantiations with different `buffer-size`
